openapi: '3.0.2'
info:
  title: Rio API
  version: '1.0'
servers:
  - url: https://localhost:3000/api
paths:
  /v1/internal/products:
    get:
      tags:
        - 内部
      summary: 一覧取得
      description: 登録済みエロゲ一覧の取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalList'
    post:
      tags:
        - 内部
      summary: 追加
      description: エロゲの新規追加
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternalAdd'
      responses:
        '201':
          description: Created
  /v1/internal/products/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    put:
      tags:
        - 内部
      summary: 更新
      description: エロゲの更新
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternalAdd'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - 内部
      summary: 削除
      description: エロゲの削除
      responses:
        '204':
          description: No Content
  /v1/internal/products/{id}/status:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    put:
      tags:
        - 内部
      summary: 攻略状態更新
      description: 攻略ルートの攻略状態を更新
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternalStatusUpdate'
      responses:
        '200':
          description: OK
  /v1/dmm/products:
    get:
      tags:
        - DMM
      summary: DMM商品情報取得API
      description: DMM商品情報APIでFANZAにあるエロゲの情報を取得
      parameters:
        - name: cid
          in: query
          description: 商品ID
          required: false
          schema:
            type: string
        - name: keyword
          in: query
          description: キーワード
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DMMItem'
  /v1/dmm/makers:
    get:
      tags:
        - DMM
      summary: DMMメーカー検索API
      description: DMMメーカー検索APIでFANZAに登録されているエロゲメーカーの情報を取得
      parameters:
        - name: rudy
          in: query
          description: ふりがな（先頭一致）
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DMMMaker'
  /v1/dmm/authors:
    get:
      tags:
        - DMM
      summary: DMM作者検索API
      description: DMM作者検索APIでFANZAに登録されている原画家の情報を取得
      parameters:
        - name: ruby
          in: query
          description: ふりがな（先頭一致）
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DMMAuthor'
  /v1/scape/products:
    get:
      tags:
        - エロゲー批評空間
      summary: エロゲー批評空間情報取得API（実装未定）
      description: エロゲー批評空間からエロゲの情報を取得
      parameters:
        - name: id
          in: query
          description: ID
          required: false
          schema:
            type: integer
        - name: title
          in: query
          description: タイトル（部分検索）
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScapeItem'
  /v1/seiya/products:
    get:
      tags:
        - 誠也の部屋
      summary: 誠也の部屋一覧取得API
      description: 誠也の部屋から指定されたタイトルに一致するエロゲを取得
      parameters:
        - name: title
          in: query
          description: タイトル（部分一致）
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeiyaItem'
  /v1/seiya/routes:
    get:
      tags:
        - 誠也の部屋
      summary: 誠也の部屋攻略ルート一覧API
      description: 誠也の部屋の攻略ページURLから攻略ルートの一覧を取得
      parameters:
        - name: url
          in: query
          description: 誠也の部屋の攻略ページURL
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeiyaRoute'
components:
  schemas:
    InternalList:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              content_id:
                type: string
              title:
                type: string
              dmm_url:
                type: string
                format: url
              image_url:
                type: string
                format: url
              thumbnail_url:
                type: string
                format: url
              date:
                type: string
              maker:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
              author:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
              cheat_url:
                type: string
                format: url
              routes:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    status:
                      type: integer
                      description: |-
                        0: 未攻略  
                        1: 攻略中  
                        2: 攻略済み
                      enum:
                        - 0
                        - 1
                        - 2
              engine:
                type: string
                description: スクリプトエンジン
              note:
                type: string
                description: 備考
              exe_path:
                type: string
                description: 実行ファイルの場所
    InternalAdd:
      type: object
      required:
        - title
      properties:
        content_id:
          type: string
        title:
          type: string
        dmm_url:
          type: string
          format: url
        image_url:
          type: string
          format: url
        thumbnail_url:
          type: string
          format: url
        date:
          type: string
        maker:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
        author:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
        cheat_url:
          type: string
          format: url
        routes:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              status:
                type: integer
                description: |-
                  0: 未攻略  
                  1: 攻略中  
                  2: 攻略済み
                enum:
                  - 0
                  - 1
                  - 2
        engine:
          type: string
          description: スクリプトエンジン
        note:
          type: string
          description: 備考
        exe_path:
          type: string
          description: 実行ファイルの場所
    InternalStatusUpdate:
      type: object
      properties:
        routes:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              status:
                type: integer
                enum:
                  - 0
                  - 1
                  - 2
    DMMItem:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          description: 先頭100件のみ返却
          items:
            type: object
            properties:
              content_id:
                type: string
              title:
                type: string
              dmm_url:
                type: string
                format: url
              image_url:
                type: string
                format: url
              thumbnail_url:
                type: string
                format: url
              date:
                type: string
              maker:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
              author:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    ruby:
                      type: string
    DMMMaker:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
    DMMAuthor:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
    ScapeItem:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          description: 先頭100件のみ返却
          items:
            type: object
            properties:
              id:
                  type: string
              title:
                type: string
    SeiyaItem:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          description: 先頭100件のみ返却
          items:
            type: object
            properties:
              title:
                type: string
              url:
                  type: string
    SeiyaRoute:
      type: object
      properties:
        routes:
          type: array
          items:
            type: string
